### ISSUE TITLE
cmake error on soolin

### ISSUE THREAD

**Issue by jjacob** [uobdic/Bristol-PHYS14#12]
When trying to set up the standalone Bristol Analysis Software (https://github.com/BristolTopGroup/AnalysisSoftware) on the new SLC6 soolin, in the readme, the line 

cmake CMakeLists.txt

fails with the following output:

-- Building Bristol Analysis Software on Linux
-- Using compiler GNU
-- Found Root 6.00/02 in /software/root/v6.00.02/bin/root
-- ** ROOT Include path: /software/root/v6.00.02/include
-- ** ROOT Library path: /software/root/v6.00.02/lib
-- ** ROOT Libraries: -L/software/root/v6.00.02/lib -lCore -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic -L/software/root/v6.00.02/lib -lGui -pthread -std=c++11 -Wno-deprecated-declarations -m64 -I/software/root/v6.00.02/include -m64 -pthread -lm -ldl -rdynamic -pthread -std=c++11 -Wno-deprecated-declarations -m64
Boost  found.
Found Boost components:
   filesystem;system;python;program_options;unit_test_framework
-- ** Boost Include path: Boost_INCLUDE_DIR-NOTFOUND
-- ** Boost Library path: /usr/lib64
-- ** Boost Libraries: optimized;boost_filesystem-mt-shared;debug;boost_filesystem-mt-shared-debug;optimized;boost_system-mt-shared;debug;boost_system-mt-shared-debug;optimized;boost_python-mt-shared;debug;boost_python-mt-shared-debug;optimized;boost_program_options-mt-shared;debug;boost_program_options-mt-shared-debug;optimized;boost_unit_test_framework-mt-shared;debug;boost_unit_test_framework-mt-shared-debug
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PythonLibs: Found unsuitable version "2.6.6", but required
  is at least "2.7" (found /usr/lib64/libpython2.6.so)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindPythonLibs.cmake:197 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:43 (find_package)

-- Configuring incomplete, errors occurred!
See also "/storage/phjaj/02_Analysis/AnalysisSoftware/CMakeFiles/CMakeOutput.log".

**Comment by kreczko** [comment]
Please try again, should work now

**Comment by jjacob** [comment]
Tried standalone recipe again on soolin and at the make command, it fails complaining about something to do with c++:

[  1%] Building CXX object CMakeFiles/AnalysisSoftware_test.dir/test/simpletest.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [CMakeFiles/AnalysisSoftware_test.dir/test/simpletest.cpp.o] Error 1
make[1]: *** [CMakeFiles/AnalysisSoftware_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] [  2%] [  3%] [  4%] [  5%] [  7%] [  7%] [  8%] [  9%] [ 10%] [ 11%] [ 12%] Building CXX object CMakeFiles/AnalysisSoftware.dir/src/EventWeightProvider.cpp.o
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/BTagWeight.cpp.o
[ 13%] Building CXX object CMakeFiles/AnalysisSoftware.dir/src/BTagWeight2011.cpp.o
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/HistHelpers/StringOperations.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/Taggers/ConversionTagger.cpp.o
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/ChiSquaredThreeJetsTopPairReconstruction.cpp.o
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/HistHelpers/THCollection.cpp.o
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/BTagWeight.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/EventWeightProvider.cpp.o] Error 1
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/BTagWeight2011.cpp.o] Error 1
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/HistHelpers/StringOperations.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/HistHelpers/HistogramManager.cpp.o
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/Taggers/ConversionTagger.cpp.o] Error 1
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/TopMassDifferenceTTbarReco.cpp.o
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/ChiSquaredThreeJetsTopPairReconstruction.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/HistHelpers/THCollection.cpp.o] Error 1
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/BasicNeutrinoReconstruction.cpp.o
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/HistHelpers/HistogramManager.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/HistHelpers/Histogram.cpp.o
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/TopMassDifferenceTTbarReco.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/ChiSquaredBasedTopPairReconstruction.cpp.o
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/BasicNeutrinoReconstruction.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/HistHelpers/Histogram.cpp.o] Error 1
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/ChiSquaredBasedTopPairReconstruction.cpp.o] Error 1
Building CXX object CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/NeutrinoReconstructionByApproximation.cpp.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [CMakeFiles/AnalysisSoftware.dir/src/ReconstructionModules/NeutrinoReconstructionByApproximation.cpp.o] Error 1
make[1]: *** [CMakeFiles/AnalysisSoftware.dir/all] Error 2
make: *** [all] Error 2


I also tried following the recipe for DICE (i.e. sourcing root, using cmake28 and the different library paths), but that also failed.

**Comment by kreczko** [comment]
That's OK. We will need to fix that in the AnalysisSoftware.
If you remove ```-std=c++11``` from the cmake file and clear & redo the cmake step it should work.
