### ISSUE TITLE
myproxy problem

### ISSUE THREAD

**Issue by jjacob** [uobdic/Bristol-PHYS14#14]
On soolin, I get:

```shell
myproxy-info
Unknown host "lcgrbp01.gridpp.rl.ac.uk"
Unable to connect to lcgrbp01.gridpp.rl.ac.uk
```
The following link may be useful:
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1403&L=GRIDPP-USERS&F=&S=&P=2585

**Comment by kreczko** [comment]
Old configuration got into ```/etc/profile.d/grid-env.sh```
Please log out & login & try again.

**Comment by jjacob** [comment]
Fixed, thanks. Closing issue.
